#\!/bin/bash
echo "SSH into your server and run these commands:"
echo ""
echo "cd /root/stepperslife"
echo ""
echo "# Start auth service"
echo "cd /root/stepperslife/auth-service && nohup npm start > /var/log/auth-service.log 2>&1 &"
echo ""
echo "# Start storage service" 
echo "cd /root/stepperslife/storage-service && nohup npm start > /var/log/storage-service.log 2>&1 &"
echo ""
echo "# Fix build extensions"
echo "cd /root/stepperslife && node fix-build-extensions.js"
echo ""
echo "# Update nginx config and restart"
echo "systemctl reload nginx"
echo ""
echo "# Verify services"
echo "curl -I http://localhost:3010/health"
echo "curl -I http://localhost:3011/health"
EOF < /dev/null