version: '3.8'

services:
  push-api:
    container_name: push-notification-api
    build: .
    image: agi-push-api:latest
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - agi-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: "1000:1000"
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.push-api.rule=Host(`push.agistaffers.com`)"
      - "traefik.http.routers.push-api.tls=true"
      - "traefik.http.routers.push-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.push-api.loadbalancer.server.port=3008"

networks:
  agi-network:
    external: true