name = "agi-staffers-metrics-cache"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = false
account_id = "e7282949b69e1fe1237754ae983a4900"

# KV Namespace for metrics caching
kv_namespaces = [
  { binding = "METRICS_CACHE", id = "ad538917ad91426ab4ab31671438f759", preview_id = "ad538917ad91426ab4ab31671438f759" }
]

# Routes will be set up in Cloudflare dashboard
# routes = [
#   { pattern = "api.agistaffers.com/api/metrics*", zone_name = "agistaffers.com" }
# ]

[vars]
ORIGIN_URL = "https://admin.agistaffers.com"